defaults.url=https://sentry.io/
defaults.org=klikit-po
defaults.project=klikit-consumer-app
# Using SENTRY_AUTH_TOKEN environment variable
SENTRY_AUTH_TOKEN=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